In [1]:
import pandas as pd

In [2]:
results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "XGBoost",
    ],

    "Accuracy": [
        0.9685,
        0.9785,
        0.9800,
        0.9840,
    ],

    "Precision": [
        0.6667,
        0.7273,
        0.7333,
        0.7500,
    ],

    "Recall": [
        0.1471,
        0.5882,
        0.6471,
        0.7941,
    ],

    "F1 Score": [
        0.2410,
        0.6504,
        0.6875,
        0.7714,
    ],
})

results

                 Model  Accuracy  Precision  Recall  F1 Score
0  Logistic Regression    0.9685     0.6667  0.1471    0.2410
1        Decision Tree    0.9785     0.7273  0.5882    0.6504
2        Random Forest    0.9800     0.7333  0.6471    0.6875
3              XGBoost    0.9840     0.7500  0.7941    0.7714

In [3]:
results.sort_values(
    by="F1 Score",
    ascending=False,
)

                 Model  Accuracy  Precision  Recall  F1 Score
3              XGBoost    0.9840     0.7500  0.7941    0.7714
2        Random Forest    0.9800     0.7333  0.6471    0.6875
1        Decision Tree    0.9785     0.7273  0.5882    0.6504
0  Logistic Regression    0.9685     0.6667  0.1471    0.2410

Model Selection

Four machine learning algorithms were evaluated for predictive maintenance:

Logistic Regression
Decision Tree
Random Forest
XGBoost

Evaluation was based on:

Accuracy
Precision
Recall
F1 Score

Since predictive maintenance prioritizes detecting equipment failures, Recall and F1 Score were considered more important than Accuracy alone.

XGBoost achieved:

Highest Accuracy
Highest Recall
Highest F1 Score

Therefore, XGBoost was selected as the final production model.